"""
train_elasticity_model.py — Price Elasticity Calibration (Layer 3)
=====
Uses Optuna to "discover" the hidden acceptance behavior from the
synthetic market history generated by simulate_acceptance.py.

The model learns from:
  - rate_spread:        Core price sensitivity signal
  - pd_ensemble:        Risk level drives sensitivity magnitude
  - AMT_CREDIT:         Larger loans → more shopping around
  - AMT_INCOME_TOTAL:   Income proxy for alternatives available

Outputs:
  models/v2/elasticity_model.joblib
  models/v2/elasticity_scaler.joblib
  models/v2/elasticity_features.joblib
  models/v2/elasticity_metrics.json

Usage:
    python src/models/train_elasticity_model.py
"""

import os
import sys
import json
import warnings
import numpy as np
import pandas as pd
import joblib
import yaml
import optuna
from optuna.samplers import TPESampler
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler, PolynomialFeatures
from sklearn.pipeline import Pipeline
from sklearn.metrics import roc_auc_score, log_loss, brier_score_loss
from sklearn.model_selection import StratifiedKFold, cross_val_score

warnings.filterwarnings('ignore')
optuna.logging.set_verbosity(optuna.logging.WARNING)

ROOT_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
sys.path.insert(0, ROOT_DIR)


def load_config():
    config_path = os.path.join(ROOT_DIR, 'configs', 'config.yaml')
    with open(config_path, 'r') as f:
        return yaml.safe_load(f)


def load_acceptance_history(processed_path):
    """Load the synthetic acceptance history."""
    path = os.path.join(processed_path, 'acceptance_history.csv')
    if not os.path.exists(path):
        raise FileNotFoundError(
            f"acceptance_history.csv not found at {path}\n"
            "Run: python src/data/simulate_acceptance.py first."
        )
    df = pd.read_csv(path)
    print(f"📂 Loaded acceptance history: {len(df):,} rows")
    print(f"   Acceptance rate: {df['ACCEPTED'].mean():.1%}")
    return df


def engineer_elasticity_features(df):
    """
    Build features for the calibration model.
    We deliberately do NOT include p_accept_true (that's cheating).
    We only use what a real-world analyst would observe.
    """
    X = pd.DataFrame({
        'rate_spread':          df['rate_spread'],
        'pd_ensemble':          df['pd_ensemble'],
        'log_amt_credit':       np.log1p(df['AMT_CREDIT']),
        'log_amt_income':       np.log1p(df['AMT_INCOME_TOTAL']),
        # Interactions
        'spread_x_pd':          df['rate_spread'] * df['pd_ensemble'],
        'spread_x_log_credit':  df['rate_spread'] * np.log1p(df['AMT_CREDIT']),
        'spread_x_log_income':  df['rate_spread'] * np.log1p(df['AMT_INCOME_TOTAL']),
    })
    return X


def run_calibration():
    """Main elasticity calibration pipeline."""
    config = load_config()
    print("=" * 60)
    print("  DYNAMIC LOAN PRICING — ELASTICITY CALIBRATION")
    print("  Using V2 simulated acceptance history + Optuna")
    print("=" * 60)

    processed_path = os.path.join(ROOT_DIR, config['paths']['processed_data'])
    models_v2_path = os.path.join(ROOT_DIR, config['paths']['models'], 'v2')
    os.makedirs(models_v2_path, exist_ok=True)

    # ── Load Data ──
    df = load_acceptance_history(processed_path)
    X = engineer_elasticity_features(df)
    y = df['ACCEPTED']

    feature_cols = list(X.columns)
    print(f"\n🔧 Features for calibration: {feature_cols}")

    # ── Optuna Objective ──
    def objective(trial):
        # We need a decent C range to allow the model to learn the coefficients
        C = trial.suggest_float('C', 0.01, 10.0, log=True)
        
        # NEVER use class_weight='balanced' for elasticity! It forces predictions to ~50%
        # which destroys the realistic base rates (70-80%).
        
        scaler = StandardScaler()
        X_scaled = scaler.fit_transform(X)

        model = LogisticRegression(
            C=C,
            class_weight=None,
            solver='lbfgs',
            max_iter=1000,
            random_state=42
        )

        # 5-fold stratified CV optimizing for Probability Calibration (Log-Loss)
        cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
        scores = cross_val_score(model, X_scaled, y, cv=cv, scoring='neg_log_loss')
        return scores.mean()

    print(f"\n🚀 Starting Optuna Calibration (50 Trials)...")
    study = optuna.create_study(
        direction="maximize",  # We maximize negative log-loss (= minimize log-loss)
        sampler=TPESampler(seed=42),
        study_name="elasticity_calibration_v2"
    )

    def log_cb(study, trial):
        if trial.number % 10 == 0:
            print(f"   Trial {trial.number:3d}: CV-LogLoss={-trial.value:.4f}")

    study.optimize(objective, n_trials=50, callbacks=[log_cb])

    print(f"\n   🏆 Best Trial:")
    print(f"      CV-LogLoss: {-study.best_value:.4f}")
    print(f"      C:          {study.best_params['C']:.4f}")

    # ── Train Champion on Full Data ──
    print("\n🏗️ Training Champion Elasticity Model on full data...")
    champion_scaler = StandardScaler()
    X_scaled_full = champion_scaler.fit_transform(X)

    champion = LogisticRegression(
        C=study.best_params['C'],
        class_weight=None,
        solver='lbfgs',
        max_iter=1000,
        random_state=42
    )
    champion.fit(X_scaled_full, y)

    # ── Evaluate on Full Data ──
    probs_full = champion.predict_proba(X_scaled_full)[:, 1]
    auc_full  = roc_auc_score(y, probs_full)
    ll_full   = log_loss(y, probs_full)
    brier     = brier_score_loss(y, probs_full)

    print(f"\n📊 Champion Full-Data Metrics (in-sample):")
    print(f"   AUC-ROC:      {auc_full:.4f}")
    print(f"   Log-Loss:     {ll_full:.4f}")
    print(f"   Brier Score:  {brier:.4f}")

    # ── Segment Validation ──
    print(f"\n📋 Acceptance Calibration by Risk Band:")
    print(f"   {'Band':8s} {'Actual':>10s} {'Predicted':>10s} {'Diff':>8s}")
    for band in ['Low', 'Medium', 'High']:
        mask = df['risk_band'] == band
        if mask.sum() > 0:
            actual   = df.loc[mask, 'ACCEPTED'].mean()
            pred     = probs_full[mask].mean()
            print(f"   {band:8s} {actual:>10.1%} {pred:>10.1%} {pred-actual:>+8.1%}")

    # ── Coefficient Interpretability ──
    print(f"\n🔍 Model Coefficients (after calibration):")
    for feat, coef in zip(feature_cols, champion.coef_[0]):
        direction = '↑ accept' if coef > 0 else '↓ accept'
        print(f"   {feat:30s}: {coef:+.4f}  ({direction})")
    print(f"   Intercept: {champion.intercept_[0]:+.4f}")

    # ── Save Artifacts ──
    joblib.dump(champion,        os.path.join(models_v2_path, 'elasticity_model.joblib'))
    joblib.dump(champion_scaler, os.path.join(models_v2_path, 'elasticity_scaler.joblib'))
    joblib.dump(feature_cols,    os.path.join(models_v2_path, 'elasticity_features.joblib'))

    metrics = {
        'version': 'V2 — Optuna-calibrated elasticity model',
        'cv_auc': float(study.best_value),
        'full_auc': float(auc_full),
        'log_loss': float(ll_full),
        'brier_score': float(brier),
        'best_params': {k: float(v) if isinstance(v, float) else v
                        for k, v in study.best_params.items()},
        'features': feature_cols,
        'n_samples': len(df),
    }
    with open(os.path.join(models_v2_path, 'elasticity_metrics.json'), 'w') as f:
        json.dump(metrics, f, indent=2)

    print(f"\n✅ Elasticity artifacts saved to: {models_v2_path}")
    print("=" * 60)


if __name__ == '__main__':
    run_calibration()
